version: "3"

services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        container_name: backend
        command: "npm start"
    
    frontend:
        stdin_open: true
        build: ./frontend
        ports: 
            - "3000:3000"
        container_name: frontend
        command: "npm start"
